spring.application.name=Student
server.port=8083
spring.datasource.url=jdbc:mysql://root:jrRTPuepwsbAsHZglyqEvtYjulzWTsBs@tramway.proxy.rlwy.net:39585/railway
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update